backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images
public_folder: /assets/images
publish_mode: editorial_workflow

collections:
  - label: "General"
    name: "general"
    files:
      - label: "Products"
        name: "products"
        file: "content/products.json"
        fields:
          - label: items
            name: items
            widget: list
            fields:
              - { label: Handle, name: handle, widget: string }
