backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images
public_folder: /assets/images
publish_mode: editorial_workflow

collections:
  - label: "General"
    name: "general"
    files:
      - label: "Products"
        name: "products"
        file: "content/products.json"
        fields:
          - label: "items"
            name: "items"
            widget: "list"
            fields:
              - label: "Handle"
                name: "handle"
                widget: "string"
              - label: "Percentage of alcohol"
                name: "percentageAlcohol"
                widget: "number"
              - label: "IBU"
                name: "IBU"
                widget: "number"
              - label: "Content"
                name: "content"
                widget: "object"
                fields: 
                  - label: "English"
                    name: "en"
                    widget: "text"

